FROM ubuntu:20.04

SHELL ["/bin/bash", "-l", "-c"] 

ENV DEBIAN_FRONTEND=noninteractive

# Install python
RUN apt-get update -y \
    && apt-get upgrade -y
RUN apt install -y language-pack-ja-base language-pack-ja
ENV LANG ja_JP.UTF-8
RUN apt install -y tzdata
ENV TZ=Asia/Tokyo 
RUN apt install -y software-properties-common
RUN apt install -y curl vim git

# Define work directory
WORKDIR /usr/src/app

# Environment variables
ENV PYTHONDONTWRITEBYTECODE 1   # Pythonがpyc filesとdiscへ書き込むことを防ぐ
ENV PYTHONUNBUFFERED 1          # Pythonが標準入出力をバッファリングすることを防ぐ

RUN add-apt-repository -y ppa:deadsnakes/ppa \
    && apt install -y python3.9
# RUN apt remove -y python3.8
RUN cd /usr/bin \
    && ln -s -f python3.9 python3 \
    && ln -s -f pydoc3.9 pydoc3 \
    && ln -s -f pygettext3.9 pygettext3 \
    && ln -s -f python3.9 python \
    && ln -s -f pydoc3.9 pydoc \
    && ln -s -f pygettext3.9 pygettext

RUN apt install -y python3-distutils \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3 get-pip.py \
    && python3 -m pip install -U pip

COPY requirements.txt ./

RUN python3 -m pip install -r requirements.txt


# シェルスクリプトをコピー
# COPY ./entrypoint*.sh /usr/src/app/
# シェルスクリプトを実行
# ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
